language: node_js
node_js:
  - 12

services:
  - docker

install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - mv udagram-kubernetes/config ${HOME}/.kube/
  - sudo apt-get install awscli
  - mkdir ${HOME}/.aws
  - mv udagram-kubernetes/credentials ${HOME}/.aws
  
before_script: []

script:
  - docker --version
  - docker build -f udagram-feed-api/Dockerfile -t  ahmeddoma/udagram-feed-api:latest udagram-feed-api
  - docker build -f udagram-user-api/Dockerfile -t  ahmeddoma/udagram-user-api:latest udagram-user-api
  - docker build -f udagram-frontend/Dockerfile -t  ahmeddoma/udagram-frontend:latest udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t  ahmeddoma/udagram-reverseproxy:latest udagram-reverseproxy
